#!/usr/bin/env node
/**
 * Rebuild catalog/servers.yaml from ground truth.
 *
 * Ground truth is, in order: the npm registry (what is actually published),
 * the published tarballs (how many tools actually ship), the official MCP
 * Registry (what clients can discover), and this repo's own servers/ tree.
 * Editorial fields (region, category, description) are carried over from the
 * previous catalog, or bootstrapped from the legacy hand-written README.
 *
 * Usage: node scripts/catalog-refresh.mjs [--limit N]
 */
import { readFileSync, writeFileSync, existsSync, readdirSync } from "node:fs";
import { join } from "node:path";
import {
  listScopePackages, packageMeta, weeklyDownloads,
  countPublishedTools, mcpRegistryEntries, mapLimit,
} from "./lib/npm.mjs";

const ROOT = new URL("..", import.meta.url).pathname;
const CATALOG = join(ROOT, "catalog/servers.yaml");

/** Editorial fields are owned by humans and must survive a refresh. */
const EDITORIAL = ["region", "category", "description", "kind", "notes", "supersededBy", "alternative"];
// Also carried over so a rate-limited lookup degrades to "last known" rather
// than silently reporting zero.
const CARRY_OVER = [...EDITORIAL, "downloadsWeekly"];

function readExistingCatalog() {
  if (!existsSync(CATALOG)) return new Map();
  const out = new Map();
  let cur = null;
  for (const line of readFileSync(CATALOG, "utf8").split("\n")) {
    if (line.startsWith("  - package: ")) {
      cur = {};
      out.set(line.slice("  - package: ".length).trim(), cur);
      continue;
    }
    const m = cur && line.match(/^    ([A-Za-z]+): (.*)$/);
    if (m && CARRY_OVER.includes(m[1])) {
      let v = m[2].trim();
      cur[m[1]] = v.startsWith('"') ? JSON.parse(v) : v;
    }
  }
  const declared = (readFileSync(CATALOG, "utf8").match(/^  - package: /gm) ?? []).length;
  if (declared !== out.size) {
    throw new Error(
      `catalog/servers.yaml is malformed: ${declared} entries on disk but ${out.size} parsed. ` +
      `Refusing to refresh, because that would silently drop curated fields.`,
    );
  }
  return out;
}

/** Salvage region/category/description from the legacy hand-maintained README. */
function readLegacyReadme() {
  const md = readFileSync(join(ROOT, "README.md"), "utf8");
  const rows = new Map();
  let region = "", category = "";
  for (const line of md.split("\n")) {
    const r = line.match(/^###\s+(.+?)\s*$/);
    if (r) { region = r[1].trim(); category = ""; continue; }
    const c = line.match(/^####\s+(.+?)\s*$/);
    if (c) { category = c[1].trim(); continue; }
    const m = line.match(/^\|\s*\[(@[^\]]+)\]\([^)]*\)\s*\|([^|]*)\|([^|]*)\|([^|]*)\|/);
    if (m) rows.set(m[1].trim(), { region, category, description: m[4].trim() });
  }
  return rows;
}

/** Servers whose source lives in this repo — the ones we can actually fix. */
function inRepoServers() {
  const dir = join(ROOT, "servers");
  const map = new Map();
  for (const name of readdirSync(dir)) {
    const pj = join(dir, name, "package.json");
    if (!existsSync(pj)) continue;
    const p = JSON.parse(readFileSync(pj, "utf8"));
    map.set(p.name, { dir: name, repoVersion: p.version, private: p.private === true });
  }
  return map;
}

function yamlString(s) {
  if (s == null) return "null";
  const str = String(s);
  return /^[\w./@-]+$/.test(str) ? str : JSON.stringify(str);
}

function emitYaml(servers, meta) {
  const lines = [
    "# GENERATED by scripts/catalog-refresh.mjs — do not hand-edit the measured",
    "# fields (npmVersion, tools, downloads, registry*). Editorial fields",
    "# (region, category, description, status, notes) are safe to edit by hand.",
    `# Last refreshed: ${meta.refreshedAt}`,
    "",
    `refreshedAt: ${meta.refreshedAt}`,
    "servers:",
  ];
  for (const s of servers) {
    lines.push(`  - package: ${yamlString(s.package)}`);
    for (const [k, v] of Object.entries(s)) {
      if (k === "package" || v === undefined) continue;
      lines.push(`    ${k}: ${typeof v === "boolean" || typeof v === "number" ? v : yamlString(v)}`);
    }
  }
  return lines.join("\n") + "\n";
}

const limitArg = process.argv.indexOf("--limit");
const LIMIT = limitArg > -1 ? Number(process.argv[limitArg + 1]) : Infinity;

const legacy = readLegacyReadme();
const existing = readExistingCatalog();
const repo = inRepoServers();

console.error("Fetching npm scope listing…");
let packages = await listScopePackages();
if (Number.isFinite(LIMIT)) {
  if (!process.argv.includes("--allow-partial")) {
    console.error("--limit would truncate the catalog; pass --allow-partial if that is intended.");
    process.exit(2);
  }
  packages = packages.slice(0, LIMIT);
}

console.error("Fetching MCP Registry entries…");
const registry = await mcpRegistryEntries();
console.error(`  registry: ${registry.size} npm identifiers`);

console.error(`Inspecting ${packages.length} packages (versions, downloads, published tool counts)…`);
let done = 0;
const rows = await mapLimit(packages, 8, async (name) => {
  const meta = await packageMeta(name);
  if (!meta.exists) {
    const prev = existing.get(name);
    console.error(`  ! ${name}: could not resolve on npm; keeping previous entry`);
    return prev ? { package: name, ...prev, status: "unresolved" } : { package: name, status: "missing" };
  }
  const [dl, tools] = await Promise.all([
    weeklyDownloads(name),
    countPublishedTools(meta.tarball),
  ]);
  if (++done % 20 === 0) console.error(`  …${done}/${packages.length}`);
  // Prefer what a human already curated; fall back to the legacy README.
  const ed = { ...(legacy.get(name) ?? {}), ...(existing.get(name) ?? {}) };
  const local = repo.get(name);
  const reg = registry.get(name);
  return {
    package: name,
    npmVersion: meta.version,
    npmPublished: meta.published,
    downloadsWeekly: dl ?? existing.get(name)?.downloadsWeekly,
    tools: tools.tools,
    toolsMethod: tools.method,
    toolsDeclared: tools.declared ?? undefined,
    toolsMismatch: tools.mismatch || undefined,
    mcpName: meta.mcpName ?? undefined,
    registryVersion: reg?.registryVersion ?? undefined,
    registryStale: reg && reg.registryVersion !== meta.version ? true : undefined,
    inRepo: local ? local.dir : undefined,
    repoVersion: local?.repoVersion,
    repoDrift: local && local.repoVersion !== meta.version ? true : undefined,
    repositoryUrl: meta.repository || undefined,
    license: meta.license ?? undefined,
    kind: ed.kind || "server",
    region: ed.region || "Unsorted",
    category: ed.category || "Other",
    description: ed.description || meta.description || "",
    notes: ed.notes || undefined,
    supersededBy: ed.supersededBy || undefined,
    unpackedSize: meta.unpackedSize ?? undefined,
    // A package under 2 KB unpacked ships no server — these are name squats.
    status: (meta.unpackedSize != null && meta.unpackedSize < 2048) || tools.tools === 0
      ? "placeholder"
      : local ? "in-repo" : "satellite",
  };
});

rows.sort((a, b) => a.package.localeCompare(b.package));
writeFileSync(CATALOG, emitYaml(rows, { refreshedAt: new Date().toISOString().slice(0, 10) }));

const placeholders = rows.filter((r) => r.status === "placeholder");
const stale = rows.filter((r) => r.registryStale);
const missing = rows.filter((r) => !r.registryVersion && r.status !== "placeholder");
console.error(`\nWrote ${CATALOG}`);
console.error(`  ${rows.length} packages | ${rows.reduce((n, r) => n + (r.tools ?? 0), 0)} tools`);
console.error(`  placeholders (empty dist): ${placeholders.length} ${placeholders.map((p) => p.package).join(", ")}`);
console.error(`  registry entries stale: ${stale.length}`);
console.error(`  published but NOT in MCP Registry: ${missing.length}`);
