#!/usr/bin/env node
/**
 * Render the server catalog into README.md / README.ru.md from catalog/servers.yaml.
 *
 * The catalog tables and the headline counts are GENERATED. Hand-editing them is
 * how this repo ended up advertising 114 servers with 112 wrong version numbers,
 * a package that was never published, and 16 real servers missing entirely.
 *
 *   node scripts/gen-catalog.mjs           # rewrite the READMEs
 *   node scripts/gen-catalog.mjs --check   # fail if they are out of date (CI)
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = new URL("..", import.meta.url).pathname;
const CHECK = process.argv.includes("--check");

const START = "<!-- CATALOG:START — generated by scripts/gen-catalog.mjs, do not edit by hand -->";
const END = "<!-- CATALOG:END -->";
const ALT_START = "<!-- ALTERNATIVES:START — generated by scripts/gen-catalog.mjs, do not edit by hand -->";
const ALT_END = "<!-- ALTERNATIVES:END -->";
const STATS_START = "<!-- CATALOG-STATS:START -->";
const STATS_END = "<!-- CATALOG-STATS:END -->";

/** Minimal reader for the flat shape catalog-refresh.mjs writes. */
function readCatalog() {
  const text = readFileSync(join(ROOT, "catalog/servers.yaml"), "utf8");
  const servers = [];
  let cur = null;
  for (const line of text.split("\n")) {
    if (line.startsWith("  - package: ")) {
      cur = { package: line.slice("  - package: ".length).trim() };
      servers.push(cur);
      continue;
    }
    const m = cur && line.match(/^    ([A-Za-z]+): (.*)$/);
    if (!m) continue;
    let v = m[2].trim();
    if (v.startsWith('"')) v = JSON.parse(v);
    else if (v === "true") v = true;
    else if (v === "false") v = false;
    else if (/^-?\d+$/.test(v)) v = Number(v);
    else if (v === "null") v = null;
    cur[m[1]] = v;
  }
  return servers;
}

/** Reader for catalog/alternatives.yaml (a list of flat records). */
function readAlternatives() {
  const text = readFileSync(join(ROOT, "catalog/alternatives.yaml"), "utf8");
  const out = [];
  let cur = null;
  for (const line of text.split("\n")) {
    if (line.startsWith("  - ")) { cur = {}; out.push(cur); }
    const m = cur && line.match(/^\s+-?\s*([a-zA-Z_]+): (.*)$/);
    if (m) cur[m[1]] = m[2].trim();
  }
  return out;
}

function renderAlternatives(alts, lang) {
  const en = lang === "en";
  const out = [
    en ? "## Where someone else's server is better" : "## Где чужой сервер лучше",
    "",
    en
      ? "A catalog that only ever recommends its own packages is a storefront. These are the servers we would install instead of ours, verified live on the date shown."
      : "Каталог, который рекомендует только свои пакеты, — это витрина, а не каталог. Вот серверы, которые мы поставили бы вместо своих; каждый проверен на указанную дату.",
    "",
    en ? "| Area | Use this instead | Why | Verified |" : "| Область | Ставьте вместо нашего | Почему | Проверено |",
    "|---|---|---|---|",
  ];
  for (const a of alts) {
    out.push(`| ${a.area} | [${a.repo}](https://github.com/${a.repo}) | ${en ? a.why_en : a.why_ru} | ${a.verifiedOn} |`);
  }
  return out.join("\n");
}

const REGION_ORDER = [
  "Russia", "Kazakhstan", "Uzbekistan", "Belarus", "Armenia", "Georgia",
  "Kyrgyzstan", "Azerbaijan", "Moldova", "Tajikistan", "Turkey",
  "Gulf (UAE + Saudi Arabia)", "Latin America (Brazil + Mexico)",
  "Africa (Nigeria + Kenya + South Africa + Algeria)",
  "Southeast Asia (Indonesia + Vietnam + Philippines)",
  "MENA (Iran + Pakistan)", "Unsorted",
];

const L = {
  en: {
    heading: "## Servers by Region",
    summary: (n, t) => `📋 Full server catalog — ${n} published packages, ${t} tools (measured, not claimed)`,
    cols: "| Package | Version | Tools | In this repo | Description |",
    note: "Versions and tool counts are read from the npm registry and the published bundles by `scripts/catalog-refresh.mjs`. CI fails if this table drifts.",
    repo: "yes", norepo: "—",
  },
  ru: {
    heading: "## Серверы по регионам",
    summary: (n, t) => `📋 Полный каталог — ${n} опубликованных пакетов, ${t} инструментов (измерено, а не заявлено)`,
    cols: "| Пакет | Версия | Инструментов | В этом репозитории | Описание |",
    note: "Версии и число инструментов берутся из npm и из опубликованных сборок скриптом `scripts/catalog-refresh.mjs`. CI падает, если таблица разошлась с реальностью.",
    repo: "да", norepo: "—",
  },
};

/** Shared libraries and the CLI are not servers; placeholders ship no server. */
function isPublishedServer(s) {
  return s.kind !== "library" && s.status !== "placeholder" && !!s.tools;
}

function renderCatalog(servers, lang) {
  const t = L[lang];
  const live = servers.filter(isPublishedServer);
  const totalTools = live.reduce((n, s) => n + (s.tools ?? 0), 0);

  const out = [t.heading, "", "<details>", `<summary><b>${t.summary(live.length, totalTools)}</b></summary>`, "", `> ${t.note}`, ""];

  const byRegion = new Map();
  for (const s of live) {
    const region = s.region && s.region !== "Unsorted" ? s.region : "Unsorted";
    if (!byRegion.has(region)) byRegion.set(region, new Map());
    const cat = byRegion.get(region);
    const key = s.category || "Other";
    if (!cat.has(key)) cat.set(key, []);
    cat.get(key).push(s);
  }

  const regions = [...byRegion.keys()].sort(
    (a, b) => (REGION_ORDER.indexOf(a) + 1 || 99) - (REGION_ORDER.indexOf(b) + 1 || 99) || a.localeCompare(b),
  );
  for (const region of regions) {
    out.push(`### ${region}`, "");
    const cats = [...byRegion.get(region).keys()].sort();
    for (const cat of cats) {
      if (cats.length > 1 || cat !== "Other") out.push(`#### ${cat}`, "");
      out.push(t.cols, "|---|---|---|---|---|");
      for (const s of byRegion.get(region).get(cat).sort((a, b) => (b.tools ?? 0) - (a.tools ?? 0))) {
        const npm = `https://www.npmjs.com/package/${s.package}`;
        out.push(`| [${s.package}](${npm}) | v${s.npmVersion} | ${s.tools} | ${s.inRepo ? `\`servers/${s.inRepo}\`` : t.norepo} | ${s.description || ""} |`);
      }
      out.push("");
    }
  }
  out.push("</details>");
  return out.join("\n");
}

function renderStats(servers, lang) {
  const live = servers.filter(isPublishedServer);
  const inRepo = live.filter((s) => s.inRepo);
  const tools = live.reduce((n, s) => n + (s.tools ?? 0), 0);
  const regions = new Set(live.map((s) => s.region).filter((r) => r && r !== "Unsorted")).size;
  return lang === "en"
    ? `> **${live.length} published MCP servers · ${tools} tools · ${inRepo.length} built in this repo · ${regions} regions · npm @theyahia**\n>\n> The largest open-source collection of MCP servers for CIS, MENA, Africa, LATAM and Southeast Asia — with every version and tool count measured from what is actually published.`
    : `> **${live.length} опубликованных MCP-серверов · ${tools} инструментов · ${inRepo.length} собраны в этом репозитории · ${regions} регионов · npm @theyahia**\n>\n> Крупнейший open-source каталог MCP-серверов для СНГ, MENA, Африки, Латинской Америки и Юго-Восточной Азии — все версии и число инструментов измерены по реально опубликованным пакетам.`;
}

function splice(text, start, end, body, file) {
  const i = text.indexOf(start);
  const j = text.indexOf(end);
  if (i === -1 || j === -1) throw new Error(`${file}: missing markers ${start} / ${end}`);
  return text.slice(0, i + start.length) + "\n\n" + body + "\n\n" + text.slice(j);
}

let drift = false;
for (const [file, lang] of [["README.md", "en"], ["README.ru.md", "ru"]]) {
  const path = join(ROOT, file);
  const servers = readCatalog();
  const before = readFileSync(path, "utf8");
  let after = splice(before, START, END, renderCatalog(servers, lang), file);
  after = splice(after, STATS_START, STATS_END, renderStats(servers, lang), file);
  after = splice(after, ALT_START, ALT_END, renderAlternatives(readAlternatives(), lang), file);
  if (before === after) { console.log(`✓ ${file} up to date`); continue; }
  if (CHECK) { console.error(`✗ ${file} is out of date — run: node scripts/gen-catalog.mjs`); drift = true; }
  else { writeFileSync(path, after); console.log(`↻ ${file} regenerated`); }
}
if (CHECK && drift) process.exit(1);
